-- RLS policies
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE location_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE location_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE location_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE lost_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE lost_commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE command_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE recovery_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE finder_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE qr_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE rescue_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE trusted_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE trusted_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence_uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION current_user_id() RETURNS UUID AS $$ SELECT auth.uid(); $$ LANGUAGE sql STABLE SECURITY DEFINER;
CREATE OR REPLACE FUNCTION user_owns_device(device_uuid UUID) RETURNS BOOLEAN AS $$ SELECT EXISTS (SELECT 1 FROM devices WHERE id=device_uuid AND user_id=auth.uid()); $$ LANGUAGE sql STABLE SECURITY DEFINER;
CREATE OR REPLACE FUNCTION user_is_admin() RETURNS BOOLEAN AS $$ SELECT EXISTS (SELECT 1 FROM admin_users WHERE user_id=auth.uid()); $$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE POLICY "Users can view own profile" ON users FOR SELECT USING (id=current_user_id());
CREATE POLICY "Users can update own profile" ON users FOR UPDATE USING (id=current_user_id());
CREATE POLICY "Users can view own security profile" ON profiles FOR SELECT USING (user_id=current_user_id());
CREATE POLICY "Owners can view their devices" ON devices FOR SELECT USING (user_id=current_user_id());
CREATE POLICY "Owners can insert their devices" ON devices FOR INSERT WITH CHECK (user_id=current_user_id());
CREATE POLICY "Owners can update their devices" ON devices FOR UPDATE USING (user_id=current_user_id());
CREATE POLICY "Owners can delete their devices" ON devices FOR DELETE USING (user_id=current_user_id());
CREATE POLICY "Owners can view device locations" ON device_locations FOR SELECT USING (EXISTS (SELECT 1 FROM devices WHERE id=device_locations.device_id AND user_id=current_user_id()));
CREATE POLICY "Owners can view lost cases" ON lost_cases FOR SELECT USING (EXISTS (SELECT 1 FROM devices WHERE id=lost_cases.device_id AND user_id=current_user_id()));
CREATE POLICY "Owners can create lost cases" ON lost_cases FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM devices WHERE id=lost_cases.device_id AND user_id=current_user_id()));
CREATE POLICY "Owners can view activity events" ON activity_events FOR SELECT USING (EXISTS (SELECT 1 FROM devices WHERE id=activity_events.device_id AND user_id=current_user_id()));
CREATE POLICY "Users can view own notifications" ON notifications FOR SELECT USING (user_id=current_user_id());
CREATE POLICY "Users can update own notifications" ON notifications FOR UPDATE USING (user_id=current_user_id());
CREATE POLICY "Anyone can view location sources" ON location_sources FOR SELECT USING (is_active=TRUE);
CREATE POLICY "Admins can view audit logs" ON audit_logs FOR SELECT USING (user_is_admin());
CREATE POLICY "Admins can view admin users" ON admin_users FOR SELECT USING (user_is_admin());
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
